Description: Remove privacy breach in docs
Author: Thomas Goirand <zigo@debian.org>
Forwarded: no
Last-Update: 2021-08-25

--- python-txaio-20.4.1.orig/README.rst
+++ python-txaio-20.4.1/README.rst
@@ -59,24 +59,3 @@
     txaio.reject(f1, RuntimeError("it failed"))
 
 Please refer to the `documentation <https://txaio.readthedocs.io/en/latest/>`_ for description and usage of the library features.
-
-
-.. |Version| image:: https://img.shields.io/pypi/v/txaio.svg
-   :target: https://pypi.python.org/pypi/txaio
-   :alt: Version
-
-.. |Build| image:: https://github.com/crossbario/txaio/workflows/main/badge.svg
-   :target: https://github.com/crossbario/txaio/actions?query=workflow%3Amain
-   :alt: Build Workflow
-
-.. |Deploy| image:: https://github.com/crossbario/txaio/workflows/deploy/badge.svg
-   :target: https://github.com/crossbario/txaio/actions?query=workflow%3Adeploy
-   :alt: Deploy Workflow
-
-.. |Coverage| image:: https://codecov.io/github/crossbario/txaio/coverage.svg?branch=master
-   :target: https://codecov.io/github/crossbario/txaio
-   :alt: Coverage
-
-.. |Docs| image:: https://readthedocs.org/projects/txaio/badge/?version=latest
-   :target: https://txaio.readthedocs.io/en/latest/
-   :alt: Docs
